import math
a=12; c=5; b= math.sqrt(a*a+c*c); kel=a+b+c; luas=round (a*c/2)
print("Diketahui :")
print("Alas = ", c, "cm")
print("Tinggi = ", a, "cm\n")
print("Jawab :")
print("Sisi A = ", a, "cm")
print("Sisi B = ", round (b), "cm")
print("Sisi C = ", c, "cm")
print("Keliling = ", round (kel), "cm")
print("Luas = ", luas, "cm")